language: cpp

compiler:
  - gcc

before_install:
  - echo $LANG

before_script:
  - echo $LC_ALL
  - cd CI_1

script:
  - g++ Source.cpp -o hello

after_success:

branches:
  only:
    - master

notifications:
  email: false

env:

os:
  - linux